### ISSUE TITLE
Host versionned version of the d3-gridding.js build file

### ISSUE THREAD

**Issue by romsson** [romsson/d3-gridding#20]
Like 
> https://d3js.org/d3-random.v1.js

Instead of (regardless the version, like 0.0.10)
> https://romsson.github.io/d3-gridding/build/d3-gridding.js

Have
> https://romsson.github.io/d3-gridding/build/d3-gridding.v0.0.10.js

**Comment by Fil** [comment]
unpkg does this for you
https://unpkg.com/d3-gridding@0.0.10/build/d3-gridding.js

**Comment by Fil** [comment]
I would recommend removing build/* from the master branch, and changing build/d3-gridding{.min,}.js in the gh-pages branch to a redirect to unpkg.
