### ISSUE TITLE
Fix build and dependencies

### ISSUE THREAD

**Issue by romsson** [romsson/d3-gridding#29]
Do some diagnostics using `npm audit`

Check status using README.MD badges

**Comment by severo** [comment]
See also `npm outdated` and https://docs.npmjs.com/misc/scripts#prepublish-and-prepare (replace `prepuplish` by `prepare` or `prepublishOnly`).

**Comment by Fil** [comment]
There is an incompatibility with https://github.com/d3/d3-scale/releases/tag/v2.2.0

building with d3-scale@2.1.2 is fine, afterwards 2 tests are broken, probably due to https://github.com/d3/d3-scale/issues/117

I think I'll just remove those tests :)

**Comment by Fil** [comment]
all fixed except d3-scale@3 which is now in #35
