### ISSUE TITLE
Can I use D3v5?

### ISSUE THREAD

**Issue by ppKrauss** [romsson/d3-gridding#33]
In nowadays  D3 is https://d3js.org/d3.v5.min.js  but examples here are using v4, and [David say something](https://david-dm.org/romsson/d3-gridding)... Can I use D3v5?

**Comment by Fil** [comment]
I use d3-gridding regularly with d3v5, with no specific issue. Maybe https://github.com/romsson/d3-gridding/blob/master/package.json#L41 could list d3 as "4-5".
